
[general]
import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 13 }
decorations = "Buttonless"

[scrolling]
multiplier = 3

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

